#include <cutl/exception.hxx>
#include <iostream>

int main( int argc, char ** argv )
{
    cutl::exception exception;
    std::cout << "place for libcutl tests" << std::endl;
    return 0;
}